version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - chmod +x ./node_modules/.bin/react-scripts  
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build